### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by achalise01** [ibm-messaging/mq-dev-samples#23]
When I run mvn clean package, it throws compilation error and says cannot find symbol.

**Comment by chughts** [comment]
What were you trying to build? There is no mvn enabled code in this repository.

**Comment by simonejain** [comment]
Are you referring to the instructions here (https://github.com/ibm-messaging/mq-dev-samples/blob/master/VideoInstructions/README.md)?

**Comment by achalise01** [comment]
@simonejain  yeah I was referring to the instructions in that link. It works now. I had to delete com file from src main and copy and paste the com folder from the root of JMS and put it in the folder I deleted the file from.
The project built and run just fine after that. 
Just need to get c sharp code working now.

**Comment by achalise01** [comment]
this issue is fixed now.

**Comment by chughts** [comment]
If building the JMS pattern samples on windows, then follow these [instructions](https://github.com/ibm-messaging/mq-dev-patterns/tree/master/JMS#building-and-running-the-samples-on-windows).
